/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */



package nessy20;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import javax.swing.JFileChooser;

/**
 *
 *
 * Interfaz gráfica para la configuración de la ubicación de Xilinx
 *
 * Created on 04-jun-2010, 16:02:42
 */
public class GUIConfig extends javax.swing.JDialog {
    
    private String rutaXilinx;
    /** Creates new form GUIConfig */
    public GUIConfig(java.awt.Frame parent, boolean modal,String ruta) {
        super(parent, modal);
        rutaXilinx=ruta;
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _lbl_HomeXilinx = new javax.swing.JLabel();
        _txt_HomeXilinx = new javax.swing.JTextField();
        _btn_HomeXilinx = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        _btnOK = new javax.swing.JButton();
        _btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración Nessy");

        _lbl_HomeXilinx.setText("Home Xilinx ISE :");

        _txt_HomeXilinx.setText(rutaXilinx);

        _btn_HomeXilinx.setText("Seleccion");
        _btn_HomeXilinx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_HomeXilinxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Configuración");

        _btnOK.setText("OK");
        _btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnOKActionPerformed(evt);
            }
        });

        _btnCancelar.setText("Cancelar");
        _btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(_lbl_HomeXilinx, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_txt_HomeXilinx, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(_btn_HomeXilinx)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(220, 220, 220))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(_btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(_btnCancelar)
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_lbl_HomeXilinx)
                    .addComponent(_btn_HomeXilinx)
                    .addComponent(_txt_HomeXilinx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_btnCancelar)
                    .addComponent(_btnOK))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btn_HomeXilinxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_HomeXilinxActionPerformed
        JFileChooser chooser;
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("C:/"));
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setMultiSelectionEnabled(false);
        chooser.setDialogTitle("Seleccionar Home Xilinx ISE");
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            rutaXilinx=chooser.getSelectedFile().getAbsolutePath();
            _txt_HomeXilinx.setText(rutaXilinx);
        } else {
            //log.info("Seleccion no llevada a cabo");
        }

    }//GEN-LAST:event__btn_HomeXilinxActionPerformed

    private void _btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnOKActionPerformed
        try {
            //TODO cargar configuracion en archivos.Properties prop = new Properties();
            InputStream is = null;
            Properties prop = new Properties();
            prop.setProperty("HomeXilinx", rutaXilinx);
            prop.store(new FileOutputStream("conf/Config.properties"), "rutas");
            this.dispose();
        } catch (IOException ex) {
            System.out.println("Fallo");
        }
}//GEN-LAST:event__btnOKActionPerformed

    private void _btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btnCancelarActionPerformed
        this.setVisible(false);
        this.dispose();
        
}//GEN-LAST:event__btnCancelarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btnCancelar;
    private javax.swing.JButton _btnOK;
    private javax.swing.JButton _btn_HomeXilinx;
    private javax.swing.JLabel _lbl_HomeXilinx;
    private javax.swing.JTextField _txt_HomeXilinx;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
